version: '3.7'
services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongoclient:
    image: mongoclient/mongoclient:latest
    hostname: mongoclient
    container_name: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3300:3000

volumes:
  mongodb_data_container:
