version: '3'
services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: testdb 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
        #- ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongoclient:
    image: mongoclient/mongoclient:latest
    hostname: mongoclient
    container_name: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3300:3000

volumes:
  mongodb_data_container:
